version: '3.5'
services:

  # needed on os x for SSH injection. May not be needed on linux. Not sure about Windows.
  sshagent:
    image: nardeas/ssh-agent:latest
    container_name: pontsun_ssh_agent
    restart: unless-stopped
    volumes:
      - "dot_ssh:/root/.ssh"
      - "socket_dir:/.ssh-agent"
    environment:
      - SSH_AUTH_SOCK=/.ssh-agent/socket

volumes:
  dot_ssh:
    name: pontsun_dot_ssh
  socket_dir:
    name: pontsun_socket_dir
